[package]
name = "reviews-service"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
actix-web = "^4"
env_logger = "0.8"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "tls-rustls"] }
dotenv = "0.15"
async-trait = "0.1.86"


